# Generated by Django 3.1.1 on 2020-09-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('owner', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_type', models.CharField(max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.account')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
